version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: inventory-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: inventory-backend
    environment:
      - MONGO_URI=mongodb://mongo:27017/inventory_db
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: inventory-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  mongo_data: